# Generated by Django 3.2.16 on 2023-01-21 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pañol_app', '0002_alter_tecnico_metros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bobina_consumo',
        ),
        migrations.DeleteModel(
            name='Bobina_hisotiral',
        ),
        migrations.DeleteModel(
            name='Descuento',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
    ]
