# Generated by Django 4.2.1 on 2023-05-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pañol_app', '0003_auto_20230121_0340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobina_consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_bobina', models.CharField(max_length=30)),
                ('tecnico', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Bobina_hisotiral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seriado_bobina', models.CharField(max_length=30)),
                ('tecnico', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnico', models.CharField(max_length=30)),
                ('equipo', models.CharField(max_length=30)),
                ('mac', models.CharField(max_length=30, unique=True)),
                ('vt', models.CharField(max_length=30)),
                ('cliente', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=60)),
                ('nombre_equipo', models.CharField(max_length=60)),
                ('seriado', models.CharField(max_length=30)),
            ],
        ),
    ]
