# Generated by Django 4.2.1 on 2023-05-24 04:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pañol_app', '0004_bobina_consumo_bobina_hisotiral_descuento_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='fecha',
            field=models.CharField(default=datetime.datetime(2023, 5, 24, 4, 11, 0, 527796, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipo',
            name='nombre_equipo',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='equiposretirados',
            unique_together={('fecha', 'tecnico', 'equipo_instalado', 'mac_instalado', 'equipo_desinstalado', 'mac_desinstalado', 'numero_vt', 'numero_cliente', 'nombre_cliente', 'dni_cliente', 'direccion_cliente', 'localidad_cliente', 'partido_cliente', 'telefono_cliente', 'region_cliente')},
        ),
    ]
