# Generated by Django 4.2.1 on 2023-05-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pañol_app', '0005_equipo_fecha_alter_equipo_nombre_equipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equiposretirados',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
